experiment: elliptic

experiment_type: exp5

model:
  nx: 1

optimizer:
  max_iter: 20000
  alpha: 1e-3
  use_backtracking: false
  armijo_c: 1e-6
  backtracking_tau: 0.5
  min_step: 1e-10
  max_backtracks: 30

solver:
  mode: hybrid

quantum:
  shots: 8192
  spectral_points: 16
  delta: 0.001
  use_preconditioning: flase

scaling:
  sizes: [16]

plots:
  show_solution: true
  show_scaling: false
  output_dir: output/elliptic_runs/noprecond2