experiment: heat

model:
  n: 32
  nx: 4

optimizer:
  max_iter: 500
  alpha: 55
  use_backtracking: true
  armijo_c: 1e-6
  backtracking_tau: 0.5
  min_step: 1e-8
  max_backtracks: 100


solver:
  mode: classical

quantum:
  shots: 8192
  spectral_points: 16
  delta: 0.001
  use_preconditioning: false

scaling:
  sizes: [16]
  iterations: 1

plots:
  show_solution: true
  show_scaling: false
  output_dir: output/classical/heat/new_results_1e_3_precision/nu_32___nx_4
