experiment: heat

model:
  n: 16
  nx: 2

optimizer:
  max_iter: 500
  alpha: 70
  use_backtracking: true
  armijo_c: 1e-6
  backtracking_tau: 0.5
  min_step: 1e-10
  max_backtracks: 120


solver:
  mode: classical

quantum:
  shots: 16384
  spectral_points: 16
  delta: 0.001
  use_preconditioning: false

scaling:
  sizes: [16]
  iterations: 1

plots:
  show_solution: true
  show_scaling: false
  output_dir: output/classical/heat/new_results_1e_3_precision/nu_16___nx_2
