experiment: elliptic2

experiment_type: exp4

alpha: 1e-2

model:
  nx: 4

optimizer:
  max_iter: 15
  alpha: 70
  use_backtracking: true
  armijo_c: 1e-6
  backtracking_tau: 0.5
  min_step: 1e-10
  max_backtracks: 100

solver:
  mode: hybrid

quantum:
  backend_mode: aer
  shots: 8192
  spectral_points: 16
  delta: 0.001
  use_preconditioning: false

scaling:
  sizes: [8]

plots:
  show_solution: false
  show_scaling: false
  show_superimposed_histories: true
  output_dir: output/elliptic2/hybrid/elliptic2_test
